#- hosts: 'all'
#  remote_user: root
#  roles:
#  - installrpm

#- hosts: 'all'
#  remote_user: root
#  roles:
#  - adduser

#- hosts: 'all'
#  remote_user: stack
#  become: false
#  roles: 
#  - udirector

#- name: installing overcloud
#  hosts: all
#  remote_user: stack
#  become: false
#  roles:
#  - overcloud
#
- name: installing httpd
  hosts: 'all'
  remote_user: stack
  tasks:


  - name: Installing Httpd 
    command: echo "Undercloud Deployed"
    register: output

#  - name: Saving the logs
#    local_action: 
#      module: copy 
#      dest: "/home/gaurav/undercloud-overcloud/lsof.log" 
#      content: "{{ output.results }}" 


#      create: yes 
#    run_once: true
#    debug: var=output.results
  - name: Setting the Undercloud status
    debug: msg={{ output.stdout }}
#    local_action: command grep "Undercloud install complete" /home/gaurav/undercloud-overcloud/lsof.log 
#    register: under

#  - include: "{{ 'success.yaml' if under.stdout == "Undercloud install complete"  else 'failure.yaml' }}"

#  - name: Undercloud | SUCCESS 
#    debug: msg="SUCCESS"
#    when: under.stdout == "Undercloud install complete."


#  - name: Undercloud  | FAILURE
#    debug: msg="FAILURE"
#    when: under.stdout !== "Undercloud install complete."

#  - include: ./success.yaml
#    when: output.stdout == "Undercloud Deployed"
 
#  - include: ./failure.yaml
#    when: "not output.stdout == 'Undercloud Deployed'"

  - name: Checking Public vip 
    wait_for: host=10.64.108.58 timeout=5
    register: ping_stat
#    delegate_to: 10.64.108.58

  - debug: msg={{ ping_stat }}
